### ISSUE TITLE
writing triples with prefix 

### ISSUE THREAD

**Issue by tamerh** [RubenVerborgh/N3.js#112]
Hi,

I am playing with the library it is very cool thanks. i have question for instance 

```
writer = N3.Writer({ prefixes: { owl: 'http://www.w3.org/2002/07/owl#', rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#', rdfs: 'http://www.w3.org/2000/01/rdf-schema#' } ,format: 'N-Triples' });

writer.addTriple({
	  subject:   'entry',
	  predicate: 'rdf:type',
	  object:    'owl:Class'
});

writer.end(function (error, result) { console.log(result); });
```

i am expecting following output  

`<entry> rdf:type owl:Class .
`
but instead i am getting 

`<entry> <rdf:type> <owl:Class>.
`
how can print it with the first way?

Thanks
Tamer

**Comment by jimsmart** [comment]
In N-Triples format, there is the definition of 'canonical' N-Triples for writers, which includes specifying a space between the object and the line terminator (because it can confuse some parsers). I don't believe a canonical form of Turtle ever made it into the spec — but I believe writing the extra space is probably 'the right thing to do', for both compatibility and human readability.

My 2p.

**Comment by RubenVerborgh** [comment]
Hi @tamerh, at the moment, N3.js does not emit a space before a period.
I'm doing this mainly for two reasons: 1) takes up less space (although gzip probably cancels that out) and 2) it's just my personal preference.

May I ask what your use case is for having a space before the period?
Is it indeed to obtain [Canonical N-Triples](https://www.w3.org/TR/n-triples/#canonical-ntriples), as mentioned by @jimsmart? Because that format has additional restrictions.
Is there software that is incompatible without the extra space?

**Comment by tamerh** [comment]
Sorry for late reply, actually I was fine with period without space. I meant about predicate, I was expecting predicate without <> when i use with prefix. Shouldn't be like that or i miss something?

**Comment by RubenVerborgh** [comment]
Ah, now I understand your question. The internal N3.js representation always uses full IRIs. So you should write instead:

```
writer.addTriple({
	  subject:   'urn:my:entry',
	  predicate: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
	  object:    'http://www.w3.org/2002/07/owl#Class'
});
```
