### ISSUE TITLE
“Chunks to triples” example in README might be misleading

### ISSUE THREAD

**Issue by betehess** [RubenVerborgh/N3.js#37]
The documentation at https://github.com/RubenVerborgh/N3.js#from-rdf-chunks-to-triples is misleading: the interleaved `console.log` do not necessarily see any triple as everything is asynchronous. Also, the call to `parser.end()` is not synchronous either.

**Comment by RubenVerborgh** [comment]
Thanks for reporting. Could you explain a little more how you think it is misleading?

The point of this example is to show that N3.js parses triples as soon as possible. N3.js is asynchronous on document level, passing triples when they're ready rather than only after the entire document has been parsed. However, each chunk that is passed to it will be parsed synchronously, because there is no need to wait for IO to happen.

This means that, if you execute the example you liked to, it will _necessarily_ output the first triple as indicated. So before the calls to `addChunk` and `end` return, the complete triples will be in `triples`.

**Comment by betehess** [comment]
> each chunk that is passed to it will be parsed synchronously

I had issues with that yesterday but I can't reproduce my problem. My bad.

I was able to check that it does work as advertised: https://github.com/w3c/banana-rdf/blob/3c1936ae31e4436e59d7af87c12bd10b80a332d2/N3.js/src/test/scala/org/w3/banana/n3js/js/N3Test.scala#L82

**Comment by RubenVerborgh** [comment]
Sometimes the timing of the parser can seem counterintuitive if you don't know its internals:

```JavaScript
var parser = N3.Parser(), parsed = 0; parser.parse(function (e, t) { t && parsed++; });
parser.addChunk('<a> <b> <c>,'); console.log(parsed); // 1
parser.end();                    console.log(parsed); // 1
```

but

```JavaScript
var parser = N3.Parser(), parsed = 0; parser.parse(function (e, t) { t && parsed++; });
parser.addChunk('<a> <b> <c>.'); console.log(parsed); // 0
parser.end();                    console.log(parsed); // 1
```

_(Hint: several terminals start with a dot, only one starts with a colon.)_

Perhaps this was what you saw yesterday. In any case, thanks for reporting; better safe than sorry.
