### ISSUE TITLE
missing breaks in switches

### ISSUE THREAD

**Issue by drewp** [RubenVerborgh/N3.js#46]
908   _readPunctuation: function (token) {
    909     var next, subject = this._subject, graph = this._graph;
    910     switch (token.type) {
    911     // A closing brace ends a graph
    912     case '}':
    913       if (this._graph === null)
    914         return this._error('Unexpected graph closing', token);
    915       this._graph = null;
    916     // A dot just ends the statement, without sharing anything with the next.
    917     case '.':

I'm still investigating, but I think there should be a 'break' after 915, and that the effect of falling through may be a null triple getting sent to parse()'s callback.

There are some other cases of unexpected fallthroughs too, like this:
```
    930     case 'IRI':
    931       if (this._supportsQuads && this._graph === null) {
...
    938         break;
    939       }
    941     case 'prefixed':
```
If 938/939 are really in the right order, I recommend a comment noting that you meant that logic.

**Comment by RubenVerborgh** [comment]
Hi @drewp, thanks for reporting.

The missing `break` is intentional. If a graph is closed—just like when a triple is “closed” with a dot—the subject needs to be cleared and we are back in the top context. Note that the unit tests break if a `break` statement is added. Also, the tests achieve full coverage, meaning that all possible paths are followed, including the fallthrough.

The second fallthrough is also intended; if the `if` statement fails, we fall through to the `default` case to throw an error.

It is true that the `parse()` callback is called one more time at the end, with `null` as triple value. This is [intentional](https://github.com/RubenVerborgh/N3.js/#parsing).
