### ISSUE TITLE
Handling of @base URI - Error: Undefined prefix ":" 

### ISSUE THREAD

**Issue by retog** [RubenVerborgh/N3.js#52]
Parsing example 10 from http://www.w3.org/2007/02/turtle/primer/ results in the error: Error: Undefined prefix ":" 

rdf-ext based jsfiddle: https://jsfiddle.net/9wgLptcs/

**Comment by RubenVerborgh** [comment]
Hi @retog, this is expected behavior according to the [RDF 1.1 spec](http://www.w3.org/TR/turtle/#prefixed-name). In fact, [this test case](http://www.w3.org/2013/TurtleTests/turtle-syntax-bad-prefix-01.ttl) explicitly demands that an undefined prefix `:` errors.

The example from 2007 you referred to is thus not in line with the spec (which came out 7 years later), and the only correct behavior of a Turtle parser is to error here.
