### ISSUE TITLE
Add utility for writing URLs through prefixes

### ISSUE THREAD

**Issue by RubenVerborgh** [RubenVerborgh/N3.js#56]
Instead of
```JavaScript
var hydra = 'http://www.w3.org/ns/hydra/core#';

var triple = { subject: 'x', object: hydra + 'property', predicate: hydra + 'freetextQuery' }
```
we could have
```JavaScript
var hydra = N3Util.prefix('http://www.w3.org/ns/hydra/core#');

var triple = { subject: 'x', object: hydra('property'), predicate: hydra('freetextQuery') };
```
in which each of the generated URLs would be cached.

Furthermore, we could have
```JavaScript
var prefixes = N3Util.prefixes();
prefixes('hydra', 'http://www.w3.org/ns/hydra/core#');

var hydra = prefixes('hydra');
var property1 = hydra('property');
var property2 = prefixes('hydra')('property');
```

where

```JavaScript
N3Util.prefix = function (uri) { return N3Util.prefixes({ '': uri })(''); }
```

**Comment by nopnop** [comment]
Hello @RubenVerborgh, 

You might be interested in [rdfprefix](https://github.com/nodys/rdfprefix) I just released.

I first thought to make a PR, so [rdfprefix](https://github.com/nodys/rdfprefix) has the same API as your draft above. But, I decide to release it in a package because the features I needed may be out of the scope of N3 (importing json-ld context).

I do not suggest to add rdfprefix as dependency because N3 is light and free of any dependency. And even if [rdfprefix](https://github.com/nodys/rdfprefix) is well tested I do not know yet if it is as standard-compliant than N3. So: feel free to extract whatever you like from there if it can help to improve N3!

**Comment by RubenVerborgh** [comment]
Hah, you beat me to it :smile:

I indeed have to avoid dependencies, but might use your unit tests or so. Thanks for letting me know!

**Comment by RubenVerborgh** [comment]
Actually, this was less work than I thought. Thanks for challenging me :wink:

**Comment by nopnop** [comment]
:+1: Nice! Haha, you're welcome :)
