### ISSUE TITLE
Add support for JSON-LD

### ISSUE THREAD

**Issue by AlasdairGray** [RubenVerborgh/N3.js#94]
This is a great library. It would be fantastic if it could also support JSON-LD.

**Comment by RubenVerborgh** [comment]
Thanks! However, this library will probably not support JSON-LD, because N3.js focuses on streaming, and JSON-LD (in general) can not be parsed in a streaming way.

However, the RDF/JS initiative will deliver a [uniform interface](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md) for all RDF libraries in JavaScript, so you would be able to plug in a JSON-LD parser alongside N3.js. [RDF-ext](https://github.com/rdf-ext/rdf-ext) already provides something like this today, and uses N3.js in the back.
